version: '3'
services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "16280:80"
    volumes:
      - ${GOPATH}/pkg:/go/pkg:delegated
      - ./:/code:delegated
      - nas1:/mnt/n1
      - nas2:/mnt/n2
volumes:
  nas1:
    driver_opts:
      type: nfs
      o: "addr=${NAS_HOSTNAME1},rw,soft,intr,nfsvers=4"
      device: ":${NAS_SHAREDIR1}"
  nas2:
    driver_opts:
      type: nfs
      o: "addr=${NAS_HOSTNAME2},rw,soft,intr,nfsvers=4"
      device: ":${NAS_SHAREDIR2}"
